export const ADD_STATE = 'ADD_STATE';
export const MAKE_LOGIN_AUTH = 'MAKE_LOGIN_AUTH';

// Request Person Data From the Server
export const START_REQUEST_PERSON_DATA = "START_REQUEST_PERSON_DATA";
export const SUCCESS_REQUEST_PERSON_DATA = "SUCCESS_REQUEST_PERSON_DATA";
export const ERROR_REQUEST_PERSON_DATA = "ERROR_REQUEST_PERSON_DATA";

// Make Login Authentication Types
export const START_REQUEST_AUTH_DATA = "START_REQUEST_AUTH_DATA";
export const SUCCESS_AUTHENTICATION_REQUEST = "SUCCESS_AUTHENTICATION_REQUEST";
export const ERROR_AUTHENTICATION_REQUEST = "ERROR_AUTHENTCATION_REQUEST";

// Request to Register to the Server
export const START_REQUEST_REGISTER_DATA = "START_REQUEST_REGISTER_DATA";
export const SUCCESS_REGISTERING_DATA = "SUCCESS_REGISTERING_DATA";
export const FAILURE_TO_REGISTER_DATA = "FAILURE_TO_REGISTER_DATA";

// Req