export const ADD_STATE = 'ADD_STATE';
export const MAKE_LOGIN_AUTH = 'MAKE_LOGIN_AUTH';
// Request Person Data From the Server types
export const START_REQUEST_PERSON_DATA = "START_REQUEST_PERSON_DATA";
export const SUCCESS_REQUEST_PERSON_DATA = "SUCCESS_REQUEST_PERSON_DATA";
export const ERROR_REQUEST_PERSON_DATA = "ERROR_REQUEST_PERSON_DATA";
// Make Login Authentication Types
export const START_REQUEST_AUTH_DATA = "START_REQUEST_AUTH_DATA";
export const SUCCESS_AUTHENTICATION_REQUEST = "SUCCESS_AUTHENTICATION_REQUEST";
export const ERROR_AUTHENTICATION_REQUEST = "ERROR_AUTHENTCATION_REQUEST";
// Request to Register to the Server types
export const START_REQUEST_REGISTER_DATA = "START_REQUEST_REGISTER_DATA";
export const SUCCESS_REGISTERING_DATA = "SUCCESS_REGISTERING_DATA";
export const FAILURE_TO_REGISTER_DATA = "FAILURE_TO_REGISTER_DATA";
// Check client auth with Token types
export const START_REQUEST_REFRESH_TOKEN = "START_REQUEST_REFRESH_TOKEN";
export const SUCCESS_VALIDATING_CLIENT_TOKEN = "SUCCESS_VALIDATING_CLIENT_TOKEN";
export const ERROR_VALIDATING_CLIENT_TOKEN = "ERROR_VALIDATING_CLIENT_TOKEN";
// Logout types
export const MAKE_LOGOUT_REQUEST_WITH_TOKEN = "MAKE_LOGOUT_REQUEST_WITH_TOKEN";
// Student request types
export const RESET_REQUEST_STATE = "RESET_REQUEST_STATE";
export const START_TODO_REQUEST = "START_TODO_REQUEST";
export const DELETE_STUDENT_RECORDS = "DELETE_STUDENT_RECORDS";
export const FAILED_DELETE_STUDENT_RECORDS = "FAILED_DELETE_STUDENT_RECORDS";
export const INSERT_STUDENT_RECORDS = "INSERT_STUDENT_RECORDS";
export const FAILED_INSERT_SUDENT_RECORDS = "FAILED_INSERT_SUDENT_RECORDS"; 
export const UPDATE_STUDENT_RECORDS = "UPDATE_STUDENT_RECORDS";
export const FAILED_UPDATE_STUDENT_RECORDS = "FAILED_UPDATE_STUDENT_RECORDS"; 
// Teacher request types
export const START_READ_TEACHER_RECORDS = "START_READ_TEACHER_RECORDS";
export const READ_TEACHER_RECORDS = "READ_TEACHER_RECORDS";
export const FAILED_READ_TEACHER_RECORDS = "FAILED_READ_TEACHER_RECORDS";
export const DELETE_TEACHER_RECORDS = "DELETE_TEACHER_RECORDS";
export const FAILED_DELETE_TEACHER_RECORDS = "FAILED_DELETE_TEACHER_RECORDS";
export const INSERT_TEACHER_RECORDS = "INSERT_TEACHER_RECORDS";
export const FAILED_INSERT_TEACHER_RECORDS = "FAILED_INSERT_TEACHER_RECORDS";
export const UPDATE_TEACHER_RECORDS = "UPDATE_TEACHER_RECORDS";
export const FAILED_UPDATE_TEACHER_RECORDS = "FAILED_UPDATE_TEACHER_RECORDS"; 
// Class request types
export const START_READ_CLASS_RECORDS = "START_READ_CLASS_RECORDS";
export const READ_CLASS_RECORDS = "READ_CLASS_RECORDS";
export const FAILED_READ_CLASS_RECORDS = "FAILED_READ_CLASS_RECORDS";
export const DELETE_CLASS_RECORDS = "DELETE_CLASS_RECORDS";
export const FAILED_DELETE_CLASS_RECORDS = "FAILED_DELETE_CLASS_RECORDS";
export const INSERT_CLASS_RECORDS = "INSERT_CLASS_RECORDS";
export const FAILED_INSERT_CLASS_RECORDS = "FAILED_INSERT_CLASS_RECORDS";
export const UPDATE_CLASS_RECORDS = "UPDATE_CLASS_RECORDS";
export const FAILED_UPDATE_CLASS_RECORDS = "FAILED_UPDATE_CLASS_RECORDS"; 
// Subject request types
export const START_READ_SUBJECT_RECORDS = "START_READ_SUBJECT_RECORDS";
export const READ_SUBJECT_RECORDS = "READ_SUBJECT_RECORDS";
export const FAILED_READ_SUBJECT_RECORDS = "FAILED_READ_SUBJECT_RECORDS";
export const DELETE_SUBJECT_RECORDS = "DELETE_SUBJECT_RECORDS";
export const FAILED_DELETE_SUBJECT_RECORDS = "FAILED_DELETE_SUBJECT_RECORDS";
export const INSERT_SUBJECT_RECORDS = "INSERT_SUBJECT_RECORDS";
export const FAILED_INSERT_SUBJECT_RECORDS = "FAILED_INSERT_SUBJECT_RECORDS";
export const UPDATE_SUBJECT_RECORDS = "UPDATE_SUBJECT_RECORDS";
export const FAILED_UPDATE_SUBJECT_RECORDS = "FAILED_UPDATE_SUBJECT_RECORDS"; 
// KD request types
export const START_READ_COMPETENCE_RECORDS = "START_READ_COMPETENCE_RECORDS";
export const READ_COMPETENCE_RECORDS = "READ_COMPETENCE_RECORDS";
export const FAILED_READ_COMPETENCE_RECORDS = "FAILED_READ_COMPETENCE_RECORDS";
export const DELETE_COMPETENCE_RECORDS = "DELETE_COMPETENCE_RECORDS";
export const FAILED_DELETE_COMPETENCE_RECORDS = "FAILED_DELETE_COMPETENCE_RECORDS";
export const INSERT_COMPETENCE_RECORDS = "INSERT_COMPETENCE_RECORDS";
export const FAILED_INSERT_COMPETENCE_RECORDS = "FAILED_INSERT_COMPETENCE_RECORDS";
export const UPDATE_COMPETENCE_RECORDS = "UPDATE_COMPETENCE_RECORDS";
export const FAILED_UPDATE_COMPETENCE_RECORDS = "FAILED_UPDATE_COMPETENCE_RECORDS"; 
// Nilai UH types
export const START_READ_EXAM_SCORE = "START_READ_EXAM_SCORE";
export const START_READ_EXAM_SCORE_PER_MAPEL = "START_READ_EXAM_SCORE_PER_MAPEL";
export const READ_EXAM_SCORE = "READ_EXAM_SCORE";
export const READ_EXAM_SCORE_PER_MAPEL = "READ_EXAM_SCORE_PER_MAPEL";
export const FAILED_READ_EXAM_SCORE = "FAILED_READ_EXAM_SCORE";
export const FAILED_READ_EXAM_SCORE_PER_MAPEL = "FAILED_READ_EXAM_SCORE_PER_MAPEL";
// Remedy types
export const START_READ_REMEDY_STD = "START_READ_REMEDY_STD";
export const READ_REMEDY_STD = "READ_REMEDY_STD";
export const FAILED_READ_REMEDY_STD = "FAILED_READ_REMEDY_STD";
export const START_INSERT_REMEDY_SCORE = "START_INSERT_REMEDY_SCORE";
export const INSERT_REMEDY_SCORE = "INSERT_REMEDY_SCORE";
export const FAILED_INSERT_REMEDY_SCORE = "FAILED_INSERT_REMEDY_SCORE";
// Setting types
export const START_READ_SETTINGS_RECORD = "START_READ_SETTINGS_RECORD";
export const READ_SETTINGS_RECORD = "READ_SETTINGS_RECORD";
export const FAILED_READ_SETTINGS_RECORD = "FAILED_READ_SETTINGS_RECORD";
export const UPDATE_SETTING_RECORD = "UPDATE_SETTING_RECORD";
export const START_UPDATE_SETTING_RECORD = "START_UPDATE_SETTING_RECORD";
export const FAILED_UPDATE_SETTING_RECORD = "FAILED_UPDATE_SETTING_RECORD";
export const INSERT_SETTING_RECORD = "INSERT_SETTING_RECORD";
export const START_INSERT_SETTING_RECORD = "START_INSERT_SETTING_RECORD";
export const FAILED_INSERT_SETTING_RECORD = "FAILED_INSERT_SETTING_RECORD";
// Input PTPAS
export const START_READ_PTPAS_STD_RECORD = "START_READ_PTPAS_STD_RECORD";
export const READ_PTPAS_STD_RECORD = "READ_PTPAS_STD_RECORD";
export const FAILED_READ_PTPAS_STD_RECORD = "FAILED_READ_PTPAS_STD_RECORD";
export const START_READ_PTPAS_SUBJECT_RECORD = "START_READ_PTPAS_SUBJECT_RECORD"; 
export const READ_PTPAS_SUBJECT_RECORD = "READ_PTPAS_SUBJECT_RECORD"; 
export const FAILED_READ_PTPAS_SUBJECT_RECORD = "FAILED_READ_PTPAS_SUBJECT_RECORD";
export const START_INSERT_PTPAS_RECORD = "START_INSERT_PTPAS_RECORD"; 
export const INSERT_PTPAS_RECORD = "INSERT_PTPAS_RECORD"; 
export const FAILED_INSERT_PTPAS_RECORD = "FAILED_INSERT_PTPAS_RECORD"; 
// Misc types
export const START_READ_GRADE_RECORD = "START_READ_GRADE_RECORD";
export const READ_GRADE_RECORD = "READ_GRADE_RECORD";
export const FAILED_READ_GRADE_RECORD = "FAILED_READ_GRADE_RECORD";
export const START_READ_EXAM_TYPES = "START_READ_EXAM_TYPES";
export const FAILED_READ_EXAM_TYPES = "FAILED_READ_EXAM_TYPES";
export const READ_EXAM_TYPES = "READ_EXAM_TYPES";
// Remedy
export const START_READ_REMEDY_STUDENT = "START_READ_REMEDY_STUDENT";
export const READ_REMEDY_STUDENT = "READ_REMEDY_STUDENT";
export const FAILED_READ_REMEDY_STUDENT = "FAILED_READ_REMEDY_STUDENT";
export const START_READ_REMEDY_SUBJECT = "START_READ_REMEDY_SUBJECT";
export const READ_REMEDY_SUBJECT = "READ_REMEDY_SUBJECT";
export const FAILED_READ_REMEDY_SUBJECT = "FAILED_READ_REMEDY_SUBJECT";
export const START_READ_REMEDY_MATERIAL = "START_READ_REMEDY_MATERIAL";
export const READ_REMEDY_MATERIAL = "READ_REMEDY_MATERIAL";
export const FAILED_READ_REMEDY_MATERIAL = "FAILED_READ_REMEDY_MATERIAL";
export const START_READ_REMEDY_SCORE = "START_READ_REMEDY_SCORE";
export const READ_REMEDY_SCORE = "READ_REMEDY_SCORE";
export const FAILED_READ_REMEDY_SCORE = "FAILED_READ_REMEDY_SCORE";
// Exam
export const START_READ_EXAM_STUDENT = "START_READ_EXAM_STUDENT";
export const READ_EXAM_STUDENT = "READ_EXAM_STUDENT";
export const FAILED_READ_EXAM_STUDENT = "FAILED_READ_EXAM_STUDENT";
export const START_READ_EXAM_SUBJECT = "START_READ_EXAM_SUBJECT";
export const READ_EXAM_SUBJECT = "READ_EXAM_SUBJECT";
export const FAILED_READ_EXAM_SUBJECT = "FAILED_READ_EXAM_SUBJECT";
export const START_READ_EXAM_MATERIAL = "START_READ_EXAM_MATERIAL";
export const READ_EXAM_MATERIAL = "READ_EXAM_MATERIAL";
export const FAILED_READ_EXAM_MATERIAL = "FAILED_READ_EXAM_MATERIAL";
export const START_INSERT_EXAM_SCORE = "START_INSERT_EXAM_SCORE"
export const INSERT_EXAM_SCORE = "INSERT_EXAM_SCORE";
export const FAILED_INSERT_EXAM_SCORE = "FAILED_INSERT_EXAM_SCORE";
export const START_READ_EXAM_DATA = "START_READ_EXAM_DATA";
export const READ_EXAM_DATA = "READ_EXAM_DATA";
export const FAILED_READ_EXAM_DATA = "FAILED_READ_EXAM_DATA";
// Task types
export const READ_TASK_STUDENT = "READ_TASK_STUDENT";
export const START_READ_TASK_STUDENT = "START_READ_TASK_STUDENT";
export const FAILED_READ_TASK_STUDENT = "FAILED_READ_TASK_STUDENT";
export const READ_TASK_SUBJECT = "READ_TASK_SUBJECT";
export const START_READ_TASK_SUBJECT = "START_READ_TASK_SUBJECT";
export const FAILED_READ_TASK_SUBJECT = "FAILED_READ_TASK_SUBJECT";
export const READ_TASK_RESULT = "READ_TASK_RESULT";
export const START_READ_TASK_RESULT = "START_READ_TASK_RESULT";
export const FAILED_READ_TASK_RESULT = "FAILED_READ_TASK_RESULT";
export const INSERT_TASK_RESULT = "INSERT_TASK_RESULT";
export const START_INSERT_TASK_RESULT = "START_INSERT_TASK_RESULT";
export const FAILED_INSERT_TASK_RESULT = "FAILED_INSERT_TASK_RESULT";
// Report types
export const START_READ_REPORT_STUDENT = "START_READ_REPORT_STUDENT";
export const READ_REPORT_STUDENT = "READ_REPORT_STUDENT";
export const FAILED_READ_REPORT_STUDENT = "FAILED_READ_REPORT_STUDENT";
export const START_READ_REPORT_MATERIAL = "START_READ_REPORT_MATERIAL";
export const READ_REPORT_MATERIAL = "READ_REPORT_MATERIAL";
export const FAILED_READ_REPORT_MATERIAL = "FAILED_READ_REPORT_MATERIAL";
export const START_READ_REPORT_SUBJECT = "START_READ_REPORT_SUBJECT";
export const READ_REPORT_SUBJECT = "READ_REPORT_SUBJECT";
export const FAILED_READ_REPORT_SUBJECT = "FAILED_READ_REPORT_SUBJECT";
export const START_READ_REPORT_TASK_NAME = "START_READ_REPORT_TASK_NAME";
export const READ_REPORT_TASK_NAME = "READ_REPORT_TASK_NAME";
export const FAILED_READ_REPORT_TASK_NAME = "FAILED_READ_REPORT_TASK_NAME";
export const START_READ_REPORT_RESULT = "START_READ_REPORT_RESULT";
export const READ_REPORT_RESULT = "READ_REPORT_RESULT";
export const FAILED_READ_REPORT_RESULT = "FAILED_READ_REPORT_RESULT"; 
export const RESET_REPORT_RESULT_STATE = "RESET_REPORT_RESULT_STATE";

// b
export const START_READ_REPORT_TASK_STUDENT = "START_READ_REPORT_TASK_STUDENT";
export const READ_REPORT_TASK_STUDENT = "READ_REPORT_TASK_STUDENT";
export const FAILED_READ_REPORT_TASK_STUDENT = "FAILED_READ_REPORT_TASK_STUDENT";
export const START_READ_REPORT_TASK_SUBJECT = "START_READ_REPORT_TASK_SUBJECT";
export const READ_REPORT_TASK_SUBJECT = "READ_REPORT_TASK_SUBJECT";
export const FAILED_READ_REPORT_TASK_SUBJECT = "FAILED_READ_REPORT_TASK_SUBJECT";
export const START_READ_REPORT_RESULT_STUDENT = "START_READ_REPORT_RESULT_STUDENT";
export const READ_REPORT_RESULT_STUDENT = "READ_REPORT_RESULT_STUDENT";
export const FAILED_READ_REPORT_RESULT_STUDENT = "FAILED_READ_REPORT_RESULT_STUDENT";
export const START_READ_REPORT_RESULT_MATERIAL = "START_READ_REPORT_RESULT_MATERIAL";
export const READ_REPORT_RESULT_MATERIAL = "READ_REPORT_RESULT_MATERIAL";
export const FAILED_READ_REPORT_RESULT_MATERIAL = "FAILED_READ_REPORT_RESULT_MATERIAL";
export const START_READ_REPORT_RESULT_SUBJECT = "START_READ_REPORT_RESULT_SUBJECT";
export const READ_REPORT_RESULT_SUBJECT = "READ_REPORT_RESULT_SUBJECT";
export const FAILED_READ_REPORT_RESULT_SUBJECT = "FAILED_READ_REPORT_RESULT_SUBJECT";

export const GET_GRADE_WITH_CURRENT_SCHOOL_YEAR = "GET_GRADE_WITH_CURRENT_SCHOOL_YEAR";
export const PROCESS_GRADE_WITH_CURRENT_SCHOOL_YEAR = "PROCESS_GRADE_WITH_CURRENT_SCHOOL_YEAR";
export const ERROR_GET_GRADE_WITH_CURRENT_SCHOOL_YEAR = "ERROR_GET_GRADE_WITH_CURRENT_SCHOOL_YEAR";

export const GET_DASHBOARD_INFO = "GET_DASHBOARD_INFO";
export const PROCESS_DASHBOARD_INFO = "PROCESS_DASHBOARD_INFO";
export const ERROR_GET_DASHBOARD_INFO = "ERROR_GET_DASHBOARD_INFO";

export const GET_HOMEROOM_TEACHER = "GET_HOMEROOM_TEACHER";
export const PROCESS_HOMEROOM_TEACHER = "PROCESS_HOMEROOM_TEACHER";
export const ERROR_GET_HOMEROOM_TEACHER = "ERROR_GET_HOMEROOM_TEACHER"; 

export const START_READ_EKSTRA_DATA = "START_READ_EKSTRA_DATA";
export const SUCCESS_READ_EKSTRA_DATA = "SUCCESS_READ_EKSTRA_DATA";
export const FAILED_READ_EKSTRA_DATA = "FAILED_READ_EKSTRA_DATA";
export const START_INSERT_EKSTRA_DATA = "START_INSERT_EKSTRA_DATA";
export const SUCCESS_INSERT_EKSTRA_DATA = "SUCCESS_INSERT_EKSTRA_DATA";
export const FAILED_INSERT_EKSTRA_DATA = "FAILED_INSERT_EKSTRA_DATA";
export const START_UPDATE_EKSTRA_DATA = "START_UPDATE_EKSTRA_DATA";
export const SUCCESS_UPDATE_EKSTRA_DATA = "SUCCESS_UPDATE_EKSTRA_DATA";
export const FAILED_UPDATE_EKSTRA_DATA = "FAILED_UPDATE_EKSTRA_DATA";
export const START_DELETE_EKSTRA_DATA = "START_DELETE_EKSTRA_DATA";
export const SUCCESS_DELETE_EKSTRA_DATA = "SUCCESS_DELETE_EKSTRA_DATA";
export const FAILED_DELETE_EKSTRA_DATA = "FAILED_DELETE_EKSTRA_DATA";
